### ISSUE TITLE
Typeahead: mapping and labelKey incompatible?

### ISSUE THREAD

**Issue by lukaskuzmiak** [RxNT/react-jsonschema-form-extras#103]
Consider the following `schema` and `uiSchema`:

```javascript
const schema = {
  title: "Test",
  type: "object",
  properties: {
    field: { type: "integer", title: "Field" },
  }
};

const uiSchema = {
  field: {
    "ui:field": "typeahead",
    "typeahead": {
      "minLength": 0,
      "options": [{
        "label": "somethinghere",
        "id": 1
      }],
      "labelKey": "label",
      "mapping": "id"
    }
  }
};
```

Upon selecting of `somethinghere` in the Typeahead field an error is thrown:

```
One or more options does not have a valid label string. Check the `labelKey` prop to ensure that it matches the correct option key and provides a string for filtering and display.
```

If I remove the `mapping` option the error is gone but it crashes further down the road as `field` is defined as `integer` and without the `mapping` it returns the entire object.

You can replicate the behavior here - just select `somethinghere` in the box and there it is. https://codesandbox.io/s/pm3442q8zx

**Comment by sneu012** [comment]
This should be fixed in 0.9.29!
