### ISSUE TITLE
Migrate to react-bootstrap-table2? / defaultValue for datetime

### ISSUE THREAD

**Issue by slishak** [RxNT/react-jsonschema-form-extras#105]
Firstly, is there any plan to migrate to `react-bootstrap-table2`? There hasn't been an update to `react-bootstrap-table` for almost a year.

The reason I ask is that I think I've encountered a bug in `react-bootstrap-table`. I don't know if this would be fixed by `react-bootstrap-table2` but seeing as development has stopped on `react-bootstrap-table` I don't think I'd have much luck opening an issue there.

However, maybe the bug could be circumvented on the `react-jsonschema-form-extras` side. I'm not entirely sure how to go about it. Basically, I have a table column with the following properties:
```python
{
    'dataField': 'Date',
    'displayName': 'Date',
    'autoValue': True,
    'editable': {
        'readOnly': True,
        'type': 'datetime'
    },
    'dataAlign': 'left',
    'dataFormat': 'YYYY-MM-DD HH:mm'
}
```

I'd like `autoValue` to return the current time, so that when a new row is added the current time is automatically populated. This actually already appears to be _almost_ the case, looking at the line linked below, but it's not written in the correct `date-time` format so it just comes out as an invalid date.

https://github.com/AllenFang/react-bootstrap-table/blob/26d07defab759e4f9bce22d1d568690830b8d9d7/src/toolbar/InsertModalBody.js#L18

Can anyone think of a way of solving this from `react-jsonschema-form-extras` without modifying `react-boostrap-table`?

**Comment by sneu012** [comment]
Currently, we do not have plans to migrate to react-bootstrap-table2. That might be one of the long term plans for the project. 

We can add today's date to a date field in the table. We use react-date-picker with with react-bootstrap-table in order to do this.

Check the sandbox below:

[![Edit p3z45m8rpq](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/o744yq61z9)

**Comment by slishak** [comment]
Thanks for the response and detailed example! This looks like it could be almost what I need. However, if I change the format to "date-time" then it fails validation. I need to have the complete timestamp written in valid RFC 3339 format as specified by https://json-schema.org. I'm a bit confused about whether this will work, because in the example below when adding a row the current time appears in the "Date Added" column, but when submitting the form the time disappears and the form fails validation. The time also disappears for all previous rows when adding a new row.

https://codesandbox.io/s/l2n95lkoj7

**Comment by slishak** [comment]
Maybe the cause is the following line? It seems to always format the `formData` entry as `"YYYY-MM-DD"`, regardless of whether the format is `date` or `date-time`.

https://github.com/RxNT/react-jsonschema-form-extras/blob/62924fd7adf92912832805449a11b998c2aee41f/src/table/columnHeadersFactory.js#L197-L199

**Comment by slishak** [comment]
Thanks a lot, that will be very useful!

**Comment by slishak** [comment]
Thanks for the work on this, it's a very useful feature to have. However I think there's an issue as it is writing the hour in 12-hour form not 24-hour!

https://github.com/RxNT/react-jsonschema-form-extras/commit/b775be9f095b98de9cd97a84392ce812506ecfab#r32181683

**Comment by slishak** [comment]
Pull request created to fix: https://github.com/RxNT/react-jsonschema-form-extras/pull/109
