### ISSUE TITLE
Table formData not updated on row add

### ISSUE THREAD

**Issue by slishak** [RxNT/react-jsonschema-form-extras#106]
In the tables created with this package, I can't see how the `formData` is updated when a new row is added. It is updated when rows are deleted or edited (and I can see the corresponding functions in https://github.com/RxNT/react-jsonschema-form-extras/blob/master/src/table/index.js) but there doesn't appear to be any code to handle the addition of rows, so new rows (or modifications to those rows) never appear in `formData`.

**Comment by sneu012** [comment]
Maybe not the most ideal way, but we add new items to the table using the Collapsible field. 
We plan to integrate adding items to the table using default react-bootstrap-table behaviour soon.
You can find an example [here](https://codesandbox.io/s/o744yq61z9 )!

**Comment by slishak** [comment]
Thanks, this works as advertised!
