### ISSUE TITLE
rte is not working in react-jsonschema-form-extras via cdn

### ISSUE THREAD

**Issue by priyangamani** [RxNT/react-jsonschema-form-extras#108]
const uiSchema = 
"TextBox": {
  "ui:field": "rte",
  "rte": {
     "format": "html"
  }
}
How to use rte in Json ui schema.Is there any other method to render the component?

**Comment by sneu012** [comment]
This engine uses  Mozilla's react-jsonschema-forms' ```fields``` prop to display custom ui components. You can import the rte (or other components) from ```react-jsonschema-form-extras``` and pass it to ```react-jsonschema-form's```  ```Form``` using the ```fields``` prop. 
You can find a sandbox demo [here](https://codesandbox.io/s/6zq3w28n6w).

You can install ```react-jsonschema-form-extras```  through npm. I am not sure on how it works with cdn.

**Comment by priyangamani** [comment]
I tried to use in cdn.It won't work.I resolved this issues by using custom widget in react-jsonschema-form.

**Comment by priyangamani** [comment]
I tried to use via cdn.But it won't work.Resolved the issues by using custom widget rte in react-jsonschema-form.

**Comment by priyangamani** [comment]
I tried to use via cdn.But it won't work.Resolved this issues by using custom widget (quill rte) in react-jsonschema-form.
