### ISSUE TITLE
Default value for new table row

### ISSUE THREAD

**Issue by slishak** [RxNT/react-jsonschema-form-extras#115]
Is there any way to populate a new row with some default values? I know you can use `defaultCurrentDate` to add the current date (as per the following example), but how would I add default values for the "Name" and "Description" fields in the following example?

https://codesandbox.io/s/o744yq61z9

I have tried using `{"editable": {"defalutValue": "Value"}}` in the table column but it does not seem to have any effect.

**Comment by sneu012** [comment]
You can add the default values in the item schema.

https://codesandbox.io/s/empty-cdn-6rgfm

**Comment by slishak** [comment]
Works perfectly, thank you!
