### ISSUE TITLE
How to use collapsable icon

### ISSUE THREAD

**Issue by shortwavedave** [RxNT/react-jsonschema-form-extras#123]
For the collapsible field, how do you set the icon? I don't understand this in the readme:

> icon object icons configuration in enabled and disabled state
> enabled string icon, when the field is shown (default glyphicon glyphicon-chevron-down)
> disabled string icon, when field is hidden (default glyphicon glyphicon-chevron-right)
> add string icon, to use in place of an add sign (default glyphicon glyphicon-plus-sign)
> separate boolean enable

I tried this:

```
let uiSchema = {
    firstName: {
        "ui:field": "collapsible",
        collapse: {
            field: "StringField",
            icon: "glyphicon glyphicon-chevron-down"
        }
    }
}
```

But that results in an error. The default doesn't seem to show any icon

**Comment by sneu012** [comment]
There are three icons that you can add- `enabled`, `disabled` and `add`. These attributes need to be wrapped inside `icon`.

Refer to this [link](https://github.com/RxNT/react-jsonschema-form-extras/blob/master/src/CollapsibleField.js#L38)

```
let uiSchema = {
    firstName: {
        "ui:field": "collapsible",
        collapse: {
            field: "StringField",
            icon: {
                "enabled": "glyphicon glyphicon-chevron-down"
            }
        }
    }
}
```
[View on CodeSandbox](https://codesandbox.io/s/little-silence-ksd76)

**Comment by shortwavedave** [comment]
@sneu012 Thanks!
