### ISSUE TITLE
(Some) DayPicker params doesn't work

### ISSUE THREAD

**Issue by IcarusHU** [RXNT/react-jsonschema-form-extras#146]
I've added a DayPicker input, and I cannot change the date format, or add localization, also tried some other settings documented on http://react-day-picker.js.org/, and most of them didn't work. Even on your demo page: https://codesandbox.io/s/wnyl7n07zk

Can you pls fix this, and add some docs about which features are available on DayPickerInput?

  "fieldname": {
    "ui:field": "rdp",
    "rdp": {
      "dayPickerProps": {
        "todayButton": "Today", >> this works
        "showOutsideDays": true, >> this works
        "format": "DD/MM/YYYY", >> this doesn't work
        "placeholder": "DD/MM/YYYY" >> this doesn't work
      }
    }

**Comment by sneu012** [comment]
Since, format and placeholder are DayPickerInput props, move them outside dayPickerProps.
https://codesandbox.io/s/kind-shirley-xcpwx
