### ISSUE TITLE
typeAhead using form data as options input

### ISSUE THREAD

**Issue by mrehder** [RXNT/react-jsonschema-form-extras#151]
Can the options input to typeAhead be something in the form itself?
A cross-reference situation.
For example, 
One part of the form has an array of things, keyed by "Name". 
Another part of the form refers to that array of things by "Name" so a typeahead which cross references into the form data would be very useful to ensure data integrity in the formdata.

A more concrete example:
Form item 1: a list of managers - ManagersList - array of { Name, TelephoneNumber}
Form item 2: a list of franchise stores, with each store entry having the name of the manager of the store, which is a typeahead cross reference to the Name values in the ManagersList

**Comment by sneu012** [comment]
This is currently not supported in this project, however you can create a wrapper for the Typeahead and pass the options from formData by reading it from formContext.

https://github.com/rjsf-team/react-jsonschema-form/issues/925
