### ISSUE TITLE
Need complex table that links to async popup windows via button

### ISSUE THREAD

**Issue by zboldyga** [RxNT/react-jsonschema-form-extras#4]

**Comment by zboldyga** [comment]
requested documentation on the IMO plugin from Sandeep.

**Comment by zboldyga** [comment]
From Sandeep-

RxNT created a wrapper around the IMO API (e.g. their own API), and that's what they want us to use. Sandeep gave us a Postman script, attached. He also gave these instructions:

Below is the order for running the it
1.AuthenticateUser
2.LexicalSearchProblemIT
3.LexicalDetailProblemIT

The postman scripts will work but if you integrate the call in a web app it will fail the CORS check. To resolve the CORS issue could you please use a static ip which we will add in our whitelist? Let's talk about whitelisting your ip as it will be needed for all API calls

**Comment by zboldyga** [comment]
The module we're trying to build here is for the diagnoses and med history tabs. In these modules currently, clicking a '+' button opens up the IMO plugin, then whatever is selected in that plugin is added to the table. 

We should be able to make a slight variant of the asyncComplexTypeaheadField to support a button and external URL instead of a typeahead field. 

I can probably implement this in a day or so since I spent a lot of time with the field & widget behaviors. If you get here before me feel free to take a stab.

**Comment by zboldyga** [comment]
@mavarazy - sent you an email with the IMO proxy information.

**Comment by mavarazy** [comment]
@zboldyga saw it, working with a local json-server for now, and will be switching to proxy, once it's working.

**Comment by mavarazy** [comment]
IMO is a separate field, which works fine now, so we can close this issue
