### ISSUE TITLE
Cell resizing on edit

### ISSUE THREAD

**Issue by zboldyga** [RxNT/react-jsonschema-form-extras#44]
@mavarazy 

When clicking a cell in the table, the input resizes and squishes the other table cells. In order to mirror RxNT's billing system (and to have a table that looks clean), we probably don't want any resizing to happen. The input should be the same size as the table cell.

I dug around for about 30 mins in the CSS & in the react bootstrap table project to try to come up with a solution, figured I'd run it by you and see if you had any ideas. Also, it may be better to solve this inside of the extras project and not with slap-on CSS in the encounter project, since I imagine users are generally going to want this fixed.

The main problem I ran into is that I can't see which CSS classes are being added via chrome's inspector, because the input element is dynamically inserted.

**Comment by zboldyga** [comment]
Example...

<img width="1195" alt="screen shot 2017-10-12 at 3 04 28 pm" src="https://user-images.githubusercontent.com/3706430/31521710-641ef49a-af5f-11e7-8feb-d01259a71fea.png">

**Comment by mavarazy** [comment]
There are set of rules for react-bootstrap-table that forbid/allow column expansion.

I've tried it on a column level, but it does not work for some reason, I'll see, how to make it work

**Comment by chatwithrajaram** [comment]
@mavarazy - If you using "**selectRow**" attribute, please pass "clickToExpand" as true. So that it will work.

const selectRowProp = {
      mode: 'checkbox',
      **clickToExpand: true,** // click to expand row, default is false
};

**Comment by mavarazy** [comment]
@chatwithrajaram, not sure this relates to this issue
@zboldyga I've made it work, with "editColumnClassName": with the same className
```
        {
          "dataField": "dosage",
          "className": "col-md-1",
          "columnClassName": "col-md-1",
          "editColumnClassName": "col-md-1"
        },
```
expandable is there for a different purpose, so we would not need to change anything in this project this is pure configuration, I'll update schema-generator

**Comment by mavarazy** [comment]
In order to make it easier on us, I'll add a flag to enable this by default on automatic table ui configurations
