### ISSUE TITLE
inputField: none

### ISSUE THREAD

**Issue by zboldyga** [RxNT/react-jsonschema-form-extras#46]
In some cases for the RxNT encounter, we don't want any input search field shown above the table (we might use only the plus icon next to the collapser, for example). 

It would be great to be able to exclude the inputField with a 'none' option instead of having to provide a 'typeahead' or 'asyncTypeahead'.

**Comment by mavarazy** [comment]
You can do that, by just specifying
"ui:field": "table", since you do not need complicated input
I've updated schema-generator with appropriate configurations
