### ISSUE TITLE
IMO popup enter to search

### ISSUE THREAD

**Issue by zboldyga** [RxNT/react-jsonschema-form-extras#47]
In the IMO search popup window, it seems like it would be a major convenience to be able to press enter to trigger the search. Right now in Chrome enter doesn't work, I need to click the search button.

**Comment by mavarazy** [comment]
@zboldyga This was done because of RxNT requirements.
@sandeepkesarkar can you clarify this for us?

**Comment by chatwithrajaram** [comment]
Without depending on parent window object, we can integrate form submission for IMO search. Thanks.
