### ISSUE TITLE
Lack of title form field labels

### ISSUE THREAD

**Issue by bkeating** [RxNT/react-jsonschema-form-extras#64]
Title labels seem to be entirely missing in action. I skimmed the source code quickly and looks like these extra fields are just that... fields. No label to go along with them. Are we suppose to handle this elsewhere? I'd be nice to have existing title's display. Titles are typically defined in schema:

```js
const formSchema = {
   "type": "object",
   "required": ["name", "currentSchool", "classroom", "dob", "gender"],
   "properties": {
     "name": {
       "type": "string",
       "title": "Student's First and Last Name"
     }
   }
}
```
Where *Student's First and Last Name* would be rendered to the form fields accompanied label:

<img width="580" alt="screenshot 2018-01-09 23 17 48" src="https://user-images.githubusercontent.com/157924/34756872-6254ca2a-f593-11e7-9fd2-6c2e49ec3e65.png">

But instead you just see sadness:

<img width="578" alt="screenshot 2018-01-09 23 18 39" src="https://user-images.githubusercontent.com/157924/34756879-71bde618-f593-11e7-8406-d387d14104a7.png">

Thing is, im not sure if this is the duty of the extras package, or something thats better left up react-jsonschema-form. Either way, labels are super important. I'll try to contribute if I can get some input on if this is already solved or where best to start building the support.

**Comment by bkeating** [comment]
Anything I can do to help? Happy to put the time in!

**Comment by mavarazy** [comment]
@bkeating I've tried to reproduce it and it's working as your expected case, so I guess there is something in your `uiSchema` configuration, that does not display this label, can you share full `schema` and `uiSchema`

Configuration I've used
```js
let schema = {
  "type": "object",
  "required": ["name"],
  "properties": {
    "name": {
      "type": "string",
      "title": "Student's First and Last Name"
    }
  }
};
```

**Comment by bkeating** [comment]
Thanks for getting back to me, @mavarazy. Ahh. I left out that Im using, and am experiencing this issue with the **Typeahead, based on react-bootstrap-typeahead (typeahead)**;

```js
const formSchema = {
  type: 'object',
  required: ['student'],
  properties: {
    student: {
      title: 'Students First/Last Name'
    }
  }
};
```

and my uiSchema is generated at runtime (to get that list of students). The dropdown and typeahead works as expected:

```js
const UiSchema = {
  student: {
    // 'ui:title': 'Students First/Last Name',
    'ui:field': 'typeahead',
    typeahead: {
      placeholder: 'Search Students...',
      options: _.map(this.props.studentList.student, student => (
        { id: student.id, label: student.name }
      )),
      minLength: 2
    }
  }
};
```

When I submit, the structure of that field seems correct `{id: 22, label: 'Ben Keating'},` it's just that the label/title will not show at all. I apologize if this is an ID-10T cabling user issue. I thought this was a legitimate missing feature.

**Comment by mavarazy** [comment]
@bkeating I've added a fix for this issue. Basically I've restored label logic in extras, which was ignored before. 

@sneu012 can you confirm and release a patched version.

**Comment by bkeating** [comment]
Very nice! Clean fix, too. Thank you very much for your time and attention.
