### ISSUE TITLE
typeahead doesn't include <label>

### ISSUE THREAD

**Issue by jasonmarziani** [RxNT/react-jsonschema-form-extras#71]
When a schema is set to Object, typeahead forces displayLabel = false (Label.js line 61/62). I'm using objects and had to edit Label.js to render for my <label> tags.  What's the thinking behind skipping rendering of <label> for typeahead Objects?

**Comment by sneu012** [comment]
For some of the items, we would'nt want to see the labels. For example, if we have a typeahed inside a table, we wouldn't want to see the label inside the table cell.

We have added a key "ui:forceLabelDisplay" to force displaying a label irrespective of the data type. Refer #101  for more info on using it.
