### ISSUE TITLE
Async Typeahead does not update model when user types in the input field

### ISSUE THREAD

**Issue by donalmurtagh** [RxNT/react-jsonschema-form-extras#81]
I've used the Async Typeahead to autocomplete addresses. The intended behaviour is that if a user cannot find their address in the list of suggestions (provided by the Google Maps API), then they can type their address into the field.

However, I noticed that the value stored in the model is only updated when the user chooses a suggestion. If the text in the input field is changed by typing or deleting characters, the model is not updated.

[This screen recording](https://cl.ly/2B3H1O1A3h3q) demonstrates the problem.

**Comment by donalmurtagh** [comment]
@mavarazy I've submitted a PR #82 to resolve this, have you had a chance to review it?

**Comment by mavarazy** [comment]
Just looked at it thank you for the work, it looks great.

**Comment by donalmurtagh** [comment]
@mavarazy would it be possible for you to release a new version that includes these changes?
