### ISSUE TITLE
AsyncTypeahead not fetching url

### ISSUE THREAD

**Issue by lafeber** [RxNT/react-jsonschema-form-extras#89]
I don't see any requests being made, the onChange event fires when I type but that's it. Nothing else gets logged. My code:

    import React, { Component } from "react";
    import Form from "react-jsonschema-form";
    import {AsyncTypeaheadField} from "react-jsonschema-form-extras/lib/TypeaheadField";

    const log = (type) => console.log.bind(console, type);

    let schema = {
      type: "object",
      properties: {
        user: { type: "string" }
      }
    }

    let uiSchema = {
      user: {
        "ui:field": "asyncTypeahead",
        "minLength": 1,
        "overrideOptions": false,
        "asyncTypeahead": {
           "url": "http://localhost:3001/users",
           search: (url, query) => {console.log('yes!') ; fetch(`${url}?name=${query}&maxSize=1`)}
         }
      }
    }

    class NewBoard extends Component {
        constructor(props) {
          super(props)
          this.state = {}
        }

        render() {
          return (<div><h1>Hoi</h1>
            <Form schema={schema}
                  uiSchema={uiSchema}
                  fields={{ user: AsyncTypeaheadField }}
                  onChange={log("changed")}
                  onSubmit={log("submitted")}
                  onError={log("errors")} />
            </div>)
        }
    }

    export default NewBoard

What am I doing wrong?

**Comment by sneu012** [comment]
The key for field `AsyncTypeaheadField` should be the same value you use for `ui:field` in uiSchema. I suggest you rename the key for `AsyncTypeaheadField` to `asyncTypeahead` instead of `user`.

[See Demo](https://codesandbox.io/s/w229k6ny6k)

**Comment by lafeber** [comment]
@sneu012 thank you!
